### PR TITLE
allow upgrade to lcobucci/jwt for php 8.3 compatibility

### PR DESCRIPTION
**Pull request by mathroc**
https://github.com/lcobucci/jwt/releases/tag/5.1.0

### CODE REVIEW

**Comment by SMillerDev** [comment]
It seems this needs a complete migration to JWT 5.x, since some methods no longer exist in that version.

**Comment by mathroc** [comment]
yeah, I'm not using this library myself, just starting on making our project php 8.3 compatible. so I'm not sure how it should be dealt with.

There's at least the `Push::getJsonWebToken()` method to upgrade.

I read [the upgrade documentation about it](https://github.com/lcobucci/jwt/blob/5.3.x/docs/upgrading.md#removal-of-none-algorithm) but I still don't really know what should be done. 

If you can tell me, if using `forSymmetricSigner()` with an in-memory key (which one??) is ok, I can update this merge request

**Comment by SMillerDev** [comment]
> If you can tell me, if using forSymmetricSigner() with an in-memory key (which one??) is ok, I can update this merge request

Yeah, not sure about that either. It was added in https://github.com/move-backend/ApnsPHP/pull/3/commits/f6d5ec52ad45558a5aa2e199c2cbc22ecc5ff02a for p8 keys, but I'm not sure what the exact reason for this algorithm was.

**Comment by pprkut** [comment]
I think the suggestion from the update docs to use the `Blake2b` algorithm sounds fair, at least as a first try.

Looking at the [apple docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns#2943372) it mentions that apple only supports the `ES256` algorithm, which would mean we'd have to use `ECDSA` though, based on what I found.

**Comment by pprkut** [comment]
If I understood correctly, we should use it like this now:
```
$key = InMemory::file($this->providerCertFile);
return Configuration::forSymmetricSigner(
    new Signer\Ecdsa(),
    $key,
)->builder()
 ->issuedBy($this->providerTeamId)
 ->issuedAt(new DateTimeImmutable())
 ->withHeader('kid', $this->providerKeyId)
 ->getToken(new Sha256(), $key)
 ->toString();
```

Looking at https://github.com/lcobucci/jwt/blob/5.3.x/src/Configuration.php though, none of the options passed to `forSymmetricSigner` are used for anything though. Really wondering what the value of those is, unless I'm missing something :confused:

**Comment by pprkut** [comment]
This is implemented by #79 now

**Pull request closed without merging**
